### ISSUE TITLE
[Blocker] The plugin UI comes out as a blank white window

### ISSUE THREAD

**Issue by fjaguero** [firebug/pixel-perfect#68]
Hello,

I have been using the add-on for a while without any problem but today (after a week without using it), the UI comes out as a blank white window.

![UI](http://cl.ly/image/0J051F3F122K/Image%202015-09-02%20at%2010.39.31%20a.%20m..png)

**Firefox version**
42.0a2

**Comment by janodvarko** [comment]
The problem is that some of the image files you used for layers have been removed from the disk. It generated exceptions and the popup wasn't properly initialized.

(one optional fix is to remove the data.json file from your Firefox profile directory. It's under pixel-perfect dir)

Please keep your data file as is and use the new patched version (see the link below). Layers with missing images on the local hard drive should be automatically removed from the list. Use the new version and let me know if it works for you.

http://janodvarko.cz/temp/pixel-perfect/pixelperfectplugin-2.0.7-issue.68.xpi

The patch fixes also thumbnails in the layer-list (not properly displayed in Fx42).

Thanks!
Honza

**Comment by fjaguero** [comment]
Sorry, I just removed the data.json file while reading the second paragraph. It works now, I will reproduce it again by deleting an used file.

**Comment by janodvarko** [comment]
Thanks, I want to release new version and I need someone to verify the fix.

Honza

**Comment by fjaguero** [comment]
The white screen issues is fixed but now the images are not properly loaded. I tried with different images/pages. See the broken image at the left of the UI.

![image](https://s3.amazonaws.com/f.cl.ly/items/1z09300H2D392F191n0N/Image%202015-09-04%20at%209.47.49%20a.%20m..png?t=1441352996545)

**Comment by janodvarko** [comment]
Are you still running Firefox 42?
Honza

**Comment by fjaguero** [comment]
Yes, same environment.

**Comment by janodvarko** [comment]
Hm..., I can't reproduce the problem on my machine

Can you try to create a  new fresh Firefox profile and run only PixelPerfect in it?
https://getfirebug.com/wiki/index.php/Install_Firebug_into_a_clean_profile

Can you send me the image (perhaps there could be a problem with the format?)

Honza

**Comment by fjaguero** [comment]
It works correctly with a fresh profile in both Firefox 40 and 42. :+1:

**Comment by janodvarko** [comment]
Do you have another extension (in your original profile) installed that could cause a collision?
Or do you have any tips about what could cause the problem?

Honza

**Comment by fjaguero** [comment]
I've disabled all the extensions and it did work but after enabling all of them, it still works. Quite strange. Tried to reproduce it again and it always works.

**Comment by janodvarko** [comment]
I see, ok.

Anyway, I am closing this report and I am also going to release a new version with the patch for this report included.

Feel free to make another report if you'd experience any problem.

Thanks for the help!
Honza

**Comment by fjaguero** [comment]
Great. Thanks for the support!
