### ISSUE TITLE
Positioning is fixed again

### ISSUE THREAD

**Issue by SebastianZ** [firebug/pixel-perfect#73]
Starting from Firefox 44.0 (tested in FF 44.0b2) the layer position is fixed again instead of being absolute.
This was initially [reported in issue #18](https://github.com/firebug/pixel-perfect/issues/18#issuecomment-167428148).

Sebastian

**Comment by joallard** [comment]
@SebastianZ Do you know a way one could debug this, eg see the CSS in devtools? I'd gladly fiddle with the styles and propose something myself, alas I'm not familiar enough with the extension to know how it works and how to debug.

**Comment by SebastianZ** [comment]
Add-ons can normally be debugged using the [Browser Toolbox](https://developer.mozilla.org/en-US/docs/Tools/Browser_Toolbox). Though the layers can't be inspected using it, AFAIK.

> alas I'm not familiar enough with the extension to know how it works and how to debug.

I also just filed issues for it so far, but you can set up a developer environment for Pixel Perfect as described here:

https://github.com/firebug/pixel-perfect/wiki/Developer-Guide

Then you can tweak the CSS located here:

https://github.com/firebug/pixel-perfect/blob/master/chrome/skin/classic/shared/ua.css

Sebastian

**Comment by janodvarko** [comment]
This is caused by the platform:
https://bugzilla.mozilla.org/show_bug.cgi?id=1168113
https://bugzilla.mozilla.org/show_bug.cgi?id=1230508

@ZER0: how should I proceed here?

The related anonymous content CSS is here:
https://github.com/firebug/pixel-perfect/blob/master/chrome/skin/classic/shared/ua.css#L23

The goal is to display an image (in anonymous content) that scrolls together with the content.

Also asking here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1230508#c25

Honza

**Comment by janodvarko** [comment]
Workaround: Using scroll events and manually calculate the position .

Honza
